$axure.loadCurrentPage({
  "url":"我的奖品.html",
  "generationDate":new Date(1469434947945.76),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e6d43160b0014f19bcda11b2f7b87d8b",
    "type":"Axure:Page",
    "name":"我的奖品",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0b389aa1eaf44db4b4c5d8b6225afe5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":110},
            "size":{
              "width":430,
              "height":730}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f38f7658d7ae446897898c6b6b94e615",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":110},
                "size":{
                  "width":430,
                  "height":730}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动端签到原型/u0.png"}},
{
          "id":"476e7adec56046c69f53f3604fc16fb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":110},
            "size":{
              "width":430,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"097910bc63f646b49f990719fe7e0421",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":240,
                  "y":110},
                "size":{
                  "width":430,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/移动端签到原型/u2.png"}},
{
          "id":"ebbe7affb9f7401bbc5b32a6bcf38b2a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":251,
              "y":131},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a95da7aee0ae4c69bf7461d128ce38a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":251,
                  "y":131},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 移动端签到原型",
                      "target":{
                        "targetType":"page",
                        "url":"移动端签到原型.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"53f3b067230149b0983285013e832c14",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":416,
              "y":127},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"441b735bfa26476f8b754d23dc2e6482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":416,
                  "y":127},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6a02e833d60f4214972f0da55163a375",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":251,
              "y":170},
            "size":{
              "width":399,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e61d4267239413bbc1f9f4dcd009635",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":251,
                  "y":170},
                "size":{
                  "width":399,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 签到7天送V券",
                      "objectsToFades":[{
                          "objectPath":["4cb07cb204674d8f903945aff2e8ab54"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的奖品/u8.png"}},
{
          "id":"a35c19a976f84c6495fa6357a12a6afe",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":179},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee23b158352b4d5ab80a982169984216",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":179},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的奖品/u10.png"}},
{
          "id":"c70c5895453a49f5abd6f30397c01557",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":196},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86e050fc0f0e41248b9ff0c6556c0524",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":196},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef0998afbdd04fda9d08bb522f52c668",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":251,
              "y":270},
            "size":{
              "width":399,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6eaa59e33a84118960f2ca5880ea00f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":251,
                  "y":270},
                "size":{
                  "width":399,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 签到7天送V券",
                      "objectsToFades":[{
                          "objectPath":["4cb07cb204674d8f903945aff2e8ab54"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的奖品/u8.png"}},
{
          "id":"f88f7a2c10594d6c839b1878e2ea72b8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":279},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4f51d5525954c8995b0c51e674bad50",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":279},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的奖品/u10.png"}},
{
          "id":"b19fe12b557442c39532ecc69ed3d887",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":296},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b826fea8e69348c5b50ad23da0541d2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":296},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"58ff1141bdc6461eb4624dc96fdbf38f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "location":{
              "x":251,
              "y":370},
            "size":{
              "width":399,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ebf6c84e92684703a92ffc0164044ba0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "location":{
                  "x":251,
                  "y":370},
                "size":{
                  "width":399,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 签到7天送红包",
                      "objectsToFades":[{
                          "objectPath":["c988140e45f34ddc9069125637863e94"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的奖品/u8.png"}},
{
          "id":"4872b97282f54892bf6bdf753dddd23a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":379},
            "size":{
              "width":59,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66d53ad2d3a940dfafadc375fa09f959",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":379},
                "size":{
                  "width":59,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的奖品/u10.png"}},
{
          "id":"64fc9beac1434106aa6c8194f78c84e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":347,
              "y":396},
            "size":{
              "width":105,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db853f8fbb4c4f8fa72c57edfc56d490",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":347,
                  "y":396},
                "size":{
                  "width":105,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4cb07cb204674d8f903945aff2e8ab54",
          "label":"签到7天送V券",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":290,
              "y":180},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"3bb1b0b8cee84b06aeaaf86df2871ee6",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"29c3904140634ef395dfdbad5fd1d77c",
                  "label":"",
                  "parentDynamicPanel":"4cb07cb204674d8f903945aff2e8ab54",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":340,
                      "height":260}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f58aae3e1e6647ec87ba00e99888508f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cb07cb204674d8f903945aff2e8ab54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":340,
                          "height":260}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/移动端签到原型/u109.png"}},
{
                  "id":"bcce7402a3af419191272b23be864b7b",
                  "label":"",
                  "parentDynamicPanel":"4cb07cb204674d8f903945aff2e8ab54",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":48},
                    "size":{
                      "width":290,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/移动端签到原型/u111_line.png"}},
{
                  "id":"345cc4ab2aa44c7aac193963e25105a0",
                  "label":"",
                  "parentDynamicPanel":"4cb07cb204674d8f903945aff2e8ab54",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":298,
                      "y":8},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ce65d16057b4fb7a2b4e587715f6bc2",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cb07cb204674d8f903945aff2e8ab54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":298,
                          "y":8},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 签到7天送V券",
                              "objectsToFades":[{
                                  "objectPath":["4cb07cb204674d8f903945aff2e8ab54"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4927a7b3412f44c0bca9679a5ae2c967",
                  "label":"",
                  "parentDynamicPanel":"4cb07cb204674d8f903945aff2e8ab54",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":20,
                      "y":19},
                    "size":{
                      "width":34,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"3366d4f794864678ac26b055efcd6930",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cb07cb204674d8f903945aff2e8ab54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":20,
                          "y":19},
                        "size":{
                          "width":34,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"5842f557904f4a7ab49e0332db5446a6",
                  "label":"",
                  "parentDynamicPanel":"4cb07cb204674d8f903945aff2e8ab54",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":136.5,
                      "y":116},
                    "size":{
                      "width":67,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ef6dc91185a047ba915c2bc615c8a856",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"4cb07cb204674d8f903945aff2e8ab54",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":136.5,
                          "y":116},
                        "size":{
                          "width":67,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]},
{
          "id":"c988140e45f34ddc9069125637863e94",
          "label":"签到7天送红包",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":290,
              "y":190},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"ace65e2cb56b4b3183d25ac2b27d2a68",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"dbb0a0ad5cb64ca4b428ef51b2dc9c44",
                  "label":"",
                  "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":340,
                      "height":260}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"f12a77aa40d64777a5dbc3da74520e96",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":340,
                          "height":260}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/移动端签到原型/u109.png"}},
{
                  "id":"2533f482c0ab42beb088d77b44caae95",
                  "label":"",
                  "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":48},
                    "size":{
                      "width":290,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/移动端签到原型/u111_line.png"}},
{
                  "id":"301e6f1cf3c2497f8fdf540daf736b2d",
                  "label":"",
                  "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":298,
                      "y":8},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cceb6dfc03864065a40bd0bb187a48f0",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":298,
                          "y":8},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 签到7天送红包",
                              "objectsToFades":[{
                                  "objectPath":["c988140e45f34ddc9069125637863e94"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"c4ba9f15ab914048aa2ca4fe99367b3d",
                  "label":"",
                  "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "location":{
                      "x":20,
                      "y":19},
                    "size":{
                      "width":81,
                      "height":24}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ce399434872a44709fe848a28431c9c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "location":{
                          "x":20,
                          "y":19},
                        "size":{
                          "width":81,
                          "height":24}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0c8447f784de47308140afa9dbbf724e",
                  "label":"",
                  "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                  "type":"buttonShape",
                  "styleType":"h2",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFFF0000,
                      "opacity":1},
                    "location":{
                      "x":142,
                      "y":116},
                    "size":{
                      "width":38,
                      "height":28}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"77362a0c1fa247308ec288f17114d5a4",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFFF0000,
                          "opacity":1},
                        "location":{
                          "x":142,
                          "y":116},
                        "size":{
                          "width":38,
                          "height":28}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"7be5ed595f9a4173886b098b48d18fbd",
                  "label":"",
                  "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF797979,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":173},
                    "size":{
                      "width":183,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"63c2087f57b746dab060d97206e05555",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF797979,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":173},
                        "size":{
                          "width":183,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4e0accfc08b44d71b8f922c21065f44f",
                  "label":"",
                  "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFF797979,
                      "opacity":1},
                    "location":{
                      "x":78,
                      "y":199},
                    "size":{
                      "width":110,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"55476a20245d4106bb01d64ed084523a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c988140e45f34ddc9069125637863e94",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFF797979,
                          "opacity":1},
                        "location":{
                          "x":78,
                          "y":199},
                        "size":{
                          "width":110,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]}]}]}},
  "masters":{
},
  "objectPaths":{
    "0b389aa1eaf44db4b4c5d8b6225afe5f":{
      "scriptId":"u0"},
    "f38f7658d7ae446897898c6b6b94e615":{
      "scriptId":"u1"},
    "476e7adec56046c69f53f3604fc16fb1":{
      "scriptId":"u2"},
    "097910bc63f646b49f990719fe7e0421":{
      "scriptId":"u3"},
    "ebbe7affb9f7401bbc5b32a6bcf38b2a":{
      "scriptId":"u4"},
    "a95da7aee0ae4c69bf7461d128ce38a8":{
      "scriptId":"u5"},
    "53f3b067230149b0983285013e832c14":{
      "scriptId":"u6"},
    "441b735bfa26476f8b754d23dc2e6482":{
      "scriptId":"u7"},
    "6a02e833d60f4214972f0da55163a375":{
      "scriptId":"u8"},
    "6e61d4267239413bbc1f9f4dcd009635":{
      "scriptId":"u9"},
    "a35c19a976f84c6495fa6357a12a6afe":{
      "scriptId":"u10"},
    "ee23b158352b4d5ab80a982169984216":{
      "scriptId":"u11"},
    "c70c5895453a49f5abd6f30397c01557":{
      "scriptId":"u12"},
    "86e050fc0f0e41248b9ff0c6556c0524":{
      "scriptId":"u13"},
    "ef0998afbdd04fda9d08bb522f52c668":{
      "scriptId":"u14"},
    "b6eaa59e33a84118960f2ca5880ea00f":{
      "scriptId":"u15"},
    "f88f7a2c10594d6c839b1878e2ea72b8":{
      "scriptId":"u16"},
    "a4f51d5525954c8995b0c51e674bad50":{
      "scriptId":"u17"},
    "b19fe12b557442c39532ecc69ed3d887":{
      "scriptId":"u18"},
    "b826fea8e69348c5b50ad23da0541d2c":{
      "scriptId":"u19"},
    "58ff1141bdc6461eb4624dc96fdbf38f":{
      "scriptId":"u20"},
    "ebf6c84e92684703a92ffc0164044ba0":{
      "scriptId":"u21"},
    "4872b97282f54892bf6bdf753dddd23a":{
      "scriptId":"u22"},
    "66d53ad2d3a940dfafadc375fa09f959":{
      "scriptId":"u23"},
    "64fc9beac1434106aa6c8194f78c84e9":{
      "scriptId":"u24"},
    "db853f8fbb4c4f8fa72c57edfc56d490":{
      "scriptId":"u25"},
    "4cb07cb204674d8f903945aff2e8ab54":{
      "scriptId":"u26"},
    "29c3904140634ef395dfdbad5fd1d77c":{
      "scriptId":"u27"},
    "f58aae3e1e6647ec87ba00e99888508f":{
      "scriptId":"u28"},
    "bcce7402a3af419191272b23be864b7b":{
      "scriptId":"u29"},
    "345cc4ab2aa44c7aac193963e25105a0":{
      "scriptId":"u30"},
    "2ce65d16057b4fb7a2b4e587715f6bc2":{
      "scriptId":"u31"},
    "4927a7b3412f44c0bca9679a5ae2c967":{
      "scriptId":"u32"},
    "3366d4f794864678ac26b055efcd6930":{
      "scriptId":"u33"},
    "5842f557904f4a7ab49e0332db5446a6":{
      "scriptId":"u34"},
    "ef6dc91185a047ba915c2bc615c8a856":{
      "scriptId":"u35"},
    "c988140e45f34ddc9069125637863e94":{
      "scriptId":"u36"},
    "dbb0a0ad5cb64ca4b428ef51b2dc9c44":{
      "scriptId":"u37"},
    "f12a77aa40d64777a5dbc3da74520e96":{
      "scriptId":"u38"},
    "2533f482c0ab42beb088d77b44caae95":{
      "scriptId":"u39"},
    "301e6f1cf3c2497f8fdf540daf736b2d":{
      "scriptId":"u40"},
    "cceb6dfc03864065a40bd0bb187a48f0":{
      "scriptId":"u41"},
    "c4ba9f15ab914048aa2ca4fe99367b3d":{
      "scriptId":"u42"},
    "ce399434872a44709fe848a28431c9c7":{
      "scriptId":"u43"},
    "0c8447f784de47308140afa9dbbf724e":{
      "scriptId":"u44"},
    "77362a0c1fa247308ec288f17114d5a4":{
      "scriptId":"u45"},
    "7be5ed595f9a4173886b098b48d18fbd":{
      "scriptId":"u46"},
    "63c2087f57b746dab060d97206e05555":{
      "scriptId":"u47"},
    "4e0accfc08b44d71b8f922c21065f44f":{
      "scriptId":"u48"},
    "55476a20245d4106bb01d64ed084523a":{
      "scriptId":"u49"}}});