$axure.loadCurrentPage({
  "url":"v券转赠.html",
  "generationDate":new Date(1472003847891.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"07668bc4d56943f695718d02c7a89c91",
    "type":"Axure:Page",
    "name":"V券转赠",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a77fe45f7d0a4529b83fc34635e5adb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":160},
            "size":{
              "width":450,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e773ac2208464c469e17240c684dc9d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":160},
                "size":{
                  "width":450,
                  "height":690}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的资产v券/u0.png"}},
{
          "id":"a9e93c869ab544589837cd1cdca719f3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":209},
            "size":{
              "width":450,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券/u4_line.png"}},
{
          "id":"8b3532d0c247412c80f39f9275ccd453",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":392,
              "y":177},
            "size":{
              "width":66,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40860a1f6cd443e1a3b6d52d271f3dc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":392,
                  "y":177},
                "size":{
                  "width":66,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ba6a60cb11746a681c5e7fde8ded03b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":370,
              "y":690},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 支付密码",
                      "objectsToFades":[{
                          "objectPath":["c31dffc3857f46c285bb0c30e43fd14c"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"bde2c591c2cd4b1790374009478854ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":237,
              "y":333},
            "size":{
              "width":109,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"660f47be1e3e4c27a50d18ec5a10fc4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":237,
                  "y":333},
                "size":{
                  "width":109,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9745f092add8468a9ddfcf62523ac479",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":257,
              "y":435},
            "size":{
              "width":84,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"596addd87c2c4135873601d6742da279",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":257,
                  "y":435},
                "size":{
                  "width":84,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"75145c7afd8f4c66b7e501cf7392d4fc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7,
              "opacity":1},
            "location":{
              "x":356,
              "y":324},
            "size":{
              "width":233,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ad79910552f45c59eac43672f8fdf9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFD7D7D7,
                  "opacity":1},
                "location":{
                  "x":356,
                  "y":324},
                "size":{
                  "width":233,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/v券转赠/u10.png"}},
{
          "id":"964ac19930b24b35bdbef63d60cd544a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "horizontalAlignment":"left",
            "location":{
              "x":357,
              "y":426},
            "size":{
              "width":233,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42a1af580e2f48eda5f1f55fc1d11849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "horizontalAlignment":"left",
                "location":{
                  "x":357,
                  "y":426},
                "size":{
                  "width":233,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/v券转赠/u10.png"}},
{
          "id":"c31dffc3857f46c285bb0c30e43fd14c",
          "label":"支付密码",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":false,
          "style":{
            "location":{
              "x":226.5,
              "y":229},
            "size":{
              "width":10,
              "height":10},
            "visible":false},
          "adaptiveStyles":{
},
          "scrollbars":"none",
          "fitToContent":true,
          "propagate":false,
          "diagrams":[{
              "id":"e949e208766642bb853925503fcb8c49",
              "label":"状态1",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"e387369c9f004be388ceb035db0c7622",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":17,
                      "y":0},
                    "size":{
                      "width":360,
                      "height":291}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1ca98ad9f1cf4be199440c7887bb9830",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":17,
                          "y":0},
                        "size":{
                          "width":360,
                          "height":291}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u15.png"}},
{
                  "id":"f374c943659d48fbb7df2442c224e4d6",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":47,
                      "y":57},
                    "size":{
                      "width":300,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/v券转赠/u17_line.png"}},
{
                  "id":"d16f745d21314463a5699933ec39f232",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":27,
                      "y":21},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ca4b1b79e4544339cff15e4a3fe60a5",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":27,
                          "y":21},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"fadeWidget",
                              "description":"隐藏 支付密码",
                              "objectsToFades":[{
                                  "objectPath":["c31dffc3857f46c285bb0c30e43fd14c"],
                                  "fadeInfo":{
                                    "fadeType":"hide",
                                    "options":{
                                      "showType":"none"}}}]}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"0b35b131c90746bf89db3c53c0b68eb0",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":83,
                      "y":14},
                    "size":{
                      "width":36,
                      "height":42}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2ff583d7268e422a914a88a76176160a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":83,
                          "y":14},
                        "size":{
                          "width":36,
                          "height":42}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u20.png"}},
{
                  "id":"0634d99367734c16b043961a8e79c130",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"18px",
                    "location":{
                      "x":129,
                      "y":21},
                    "size":{
                      "width":127,
                      "height":22}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"320bb7fb4b4b499ebf5ed97c40cb81c7",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"18px",
                        "location":{
                          "x":129,
                          "y":21},
                        "size":{
                          "width":127,
                          "height":22}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"bdcae0b3bb844f6f90abb7d141711b7e",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":47,
                      "y":179},
                    "size":{
                      "width":300,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/v券转赠/u17_line.png"}},
{
                  "id":"bdb9df7f79ac42b7be71aadc55837d34",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":43,
                      "y":199},
                    "size":{
                      "width":306,
                      "height":61},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1171e904a21d4d4db3fbba94e3119fec",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":43,
                          "y":199},
                        "size":{
                          "width":306,
                          "height":61},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFD7D7D7}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u25.png"}},
{
                  "id":"f2957b3bdd934a9ebd1fa49f480014f5",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":90,
                      "y":203},
                    "size":{
                      "width":10,
                      "height":55},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/v券转赠/u27_line.png"}},
{
                  "id":"c73bf790409240d8822b9460658f3761",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":139,
                      "y":205},
                    "size":{
                      "width":10,
                      "height":55},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/v券转赠/u27_line.png"}},
{
                  "id":"52ab13ac26a9476d978428cb8fde9563",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":190,
                      "y":205},
                    "size":{
                      "width":10,
                      "height":55},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/v券转赠/u27_line.png"}},
{
                  "id":"bf44353d8ba64269accd2607a310cd76",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":241,
                      "y":205},
                    "size":{
                      "width":10,
                      "height":55},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/v券转赠/u27_line.png"}},
{
                  "id":"2fba7438a3b44c3caa6905039e2dc263",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"verticalLine",
                  "styleType":"verticalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":293,
                      "y":208},
                    "size":{
                      "width":10,
                      "height":55},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/v券转赠/u27_line.png"}},
{
                  "id":"b94a0c6090bf4b36a5fe9fe73ee0cc5f",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":144,
                      "y":97},
                    "size":{
                      "width":96,
                      "height":33}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"055f2be582594150ae8a7156d09edcb3",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":144,
                          "y":97},
                        "size":{
                          "width":96,
                          "height":33}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"6dc4c6c7163f48679661046adbd55c8e",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":0,
                      "y":331},
                    "size":{
                      "width":397,
                      "height":10},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFD7D7D7}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/v券转赠/u34_line.png"}},
{
                  "id":"67046bdd3fe8419f935f0661bfc01c06",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":2,
                      "y":337},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"09fb768e0bb0467cbe7efa94ae429871",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":2,
                          "y":337},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我的资产V券2",
                              "target":{
                                "targetType":"page",
                                "url":"我的资产v券2.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"667d4ace1df443a7a96f49ceb11d6d82",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":2,
                      "y":397},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"df967cf6294641d39f7dbb5088b342c6",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":2,
                          "y":397},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"e100f04875074c458475bac01c6aed02",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":2,
                      "y":456},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"08c89ce13d9f49bcbaffaa6a217e3474",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":2,
                          "y":456},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"8e4fbaf25f5240eaaa790f3be25459a3",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":133,
                      "y":337},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"cdcfa3b91de54bfd98dd82e164474854",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":133,
                          "y":337},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "interactionMap":{
                    "onClick":{
                      "description":"OnClick",
                      "cases":[{
                          "description":"用例 1",
                          "isNewIfGroup":false,
                          "actions":[{
                              "action":"linkWindow",
                              "description":"在 当前窗口 打开 我的资产V券2",
                              "target":{
                                "targetType":"page",
                                "url":"我的资产v券2.html",
                                "includeVariables":true},
                              "linkType":"current"}]}]}},
                  "tabbable":true,
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"131de7507ecf409bbdf7c62dff382881",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":264,
                      "y":337},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"ec620a26ada54b88a9fa5c959cdada49",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":264,
                          "y":337},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"e57f7210bcac43d988b38370ced5a557",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":133,
                      "y":397},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"d1e9596833c54327b4c4b43142a28133",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":133,
                          "y":397},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"163aadf192d84c30906ed392141e8468",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":264,
                      "y":397},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9dc07d2c5cdd4123997dc3453254df50",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":264,
                          "y":397},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"e7cfca0e1c384c609fa69b9b0bccb5a9",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":133,
                      "y":456},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"7939d5a18cef4828b6c6c9152e345b7c",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":133,
                          "y":456},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"2f09d2f0a50d44088cce20ae82e39e2f",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":264,
                      "y":456},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"5b69cca382724cd98c84613adc4a1c8f",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":264,
                          "y":456},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"b806b625af454f798fc4e905ea7381de",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontSize":"28px",
                    "location":{
                      "x":133,
                      "y":515},
                    "size":{
                      "width":132,
                      "height":60},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"35ac4031c13b4edbbb3f033759b78fb1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"28px",
                        "location":{
                          "x":133,
                          "y":515},
                        "size":{
                          "width":132,
                          "height":60},
                        "borderFill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u35.png"}},
{
                  "id":"ec05f632fc46474b9c420d7326d603bc",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":317,
                      "y":537},
                    "size":{
                      "width":27,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2592acea48c14a56bac321e4415b47fc",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":317,
                          "y":537},
                        "size":{
                          "width":27,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"93b20d7ef8494088a7af9c670ddf48cd",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2},
                    "location":{
                      "x":161,
                      "y":309},
                    "size":{
                      "width":60,
                      "height":20},
                    "borderWidth":"2"},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"88b27d088d9046fe99846157521b3ca8",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fill":{
                          "fillType":"solid",
                          "color":0xFFF2F2F2},
                        "location":{
                          "x":161,
                          "y":309},
                        "size":{
                          "width":60,
                          "height":20},
                        "borderWidth":"2"},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/v券转赠/u57.png"}},
{
                  "id":"d83f32a53a454873801435c60b3228fc",
                  "label":"",
                  "parentDynamicPanel":"c31dffc3857f46c285bb0c30e43fd14c",
                  "type":"horizontalLine",
                  "styleType":"horizontalLine",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":150,
                      "y":306},
                    "size":{
                      "width":85,
                      "height":10},
                    "borderWidth":"5",
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFF2F2F2}},
                  "adaptiveStyles":{
},
                  "images":{
                    "start~":"resources/images/transparent.gif",
                    "end~":"resources/images/transparent.gif",
                    "line~":"images/v券转赠/u59_line.png"}}]}]},
{
          "id":"58a3e57369fb406fa50759b5ea3a1542",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":218,
              "y":183},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5463b7d1b0104dc7b5402b03a84dfb7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":218,
                  "y":183},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的资产V券",
                      "target":{
                        "targetType":"page",
                        "url":"我的资产v券.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "a77fe45f7d0a4529b83fc34635e5adb1":{
      "scriptId":"u0"},
    "e773ac2208464c469e17240c684dc9d2":{
      "scriptId":"u1"},
    "a9e93c869ab544589837cd1cdca719f3":{
      "scriptId":"u2"},
    "8b3532d0c247412c80f39f9275ccd453":{
      "scriptId":"u3"},
    "40860a1f6cd443e1a3b6d52d271f3dc1":{
      "scriptId":"u4"},
    "7ba6a60cb11746a681c5e7fde8ded03b":{
      "scriptId":"u5"},
    "bde2c591c2cd4b1790374009478854ed":{
      "scriptId":"u6"},
    "660f47be1e3e4c27a50d18ec5a10fc4b":{
      "scriptId":"u7"},
    "9745f092add8468a9ddfcf62523ac479":{
      "scriptId":"u8"},
    "596addd87c2c4135873601d6742da279":{
      "scriptId":"u9"},
    "75145c7afd8f4c66b7e501cf7392d4fc":{
      "scriptId":"u10"},
    "9ad79910552f45c59eac43672f8fdf9b":{
      "scriptId":"u11"},
    "964ac19930b24b35bdbef63d60cd544a":{
      "scriptId":"u12"},
    "42a1af580e2f48eda5f1f55fc1d11849":{
      "scriptId":"u13"},
    "c31dffc3857f46c285bb0c30e43fd14c":{
      "scriptId":"u14"},
    "e387369c9f004be388ceb035db0c7622":{
      "scriptId":"u15"},
    "1ca98ad9f1cf4be199440c7887bb9830":{
      "scriptId":"u16"},
    "f374c943659d48fbb7df2442c224e4d6":{
      "scriptId":"u17"},
    "d16f745d21314463a5699933ec39f232":{
      "scriptId":"u18"},
    "6ca4b1b79e4544339cff15e4a3fe60a5":{
      "scriptId":"u19"},
    "0b35b131c90746bf89db3c53c0b68eb0":{
      "scriptId":"u20"},
    "2ff583d7268e422a914a88a76176160a":{
      "scriptId":"u21"},
    "0634d99367734c16b043961a8e79c130":{
      "scriptId":"u22"},
    "320bb7fb4b4b499ebf5ed97c40cb81c7":{
      "scriptId":"u23"},
    "bdcae0b3bb844f6f90abb7d141711b7e":{
      "scriptId":"u24"},
    "bdb9df7f79ac42b7be71aadc55837d34":{
      "scriptId":"u25"},
    "1171e904a21d4d4db3fbba94e3119fec":{
      "scriptId":"u26"},
    "f2957b3bdd934a9ebd1fa49f480014f5":{
      "scriptId":"u27"},
    "c73bf790409240d8822b9460658f3761":{
      "scriptId":"u28"},
    "52ab13ac26a9476d978428cb8fde9563":{
      "scriptId":"u29"},
    "bf44353d8ba64269accd2607a310cd76":{
      "scriptId":"u30"},
    "2fba7438a3b44c3caa6905039e2dc263":{
      "scriptId":"u31"},
    "b94a0c6090bf4b36a5fe9fe73ee0cc5f":{
      "scriptId":"u32"},
    "055f2be582594150ae8a7156d09edcb3":{
      "scriptId":"u33"},
    "6dc4c6c7163f48679661046adbd55c8e":{
      "scriptId":"u34"},
    "67046bdd3fe8419f935f0661bfc01c06":{
      "scriptId":"u35"},
    "09fb768e0bb0467cbe7efa94ae429871":{
      "scriptId":"u36"},
    "667d4ace1df443a7a96f49ceb11d6d82":{
      "scriptId":"u37"},
    "df967cf6294641d39f7dbb5088b342c6":{
      "scriptId":"u38"},
    "e100f04875074c458475bac01c6aed02":{
      "scriptId":"u39"},
    "08c89ce13d9f49bcbaffaa6a217e3474":{
      "scriptId":"u40"},
    "8e4fbaf25f5240eaaa790f3be25459a3":{
      "scriptId":"u41"},
    "cdcfa3b91de54bfd98dd82e164474854":{
      "scriptId":"u42"},
    "131de7507ecf409bbdf7c62dff382881":{
      "scriptId":"u43"},
    "ec620a26ada54b88a9fa5c959cdada49":{
      "scriptId":"u44"},
    "e57f7210bcac43d988b38370ced5a557":{
      "scriptId":"u45"},
    "d1e9596833c54327b4c4b43142a28133":{
      "scriptId":"u46"},
    "163aadf192d84c30906ed392141e8468":{
      "scriptId":"u47"},
    "9dc07d2c5cdd4123997dc3453254df50":{
      "scriptId":"u48"},
    "e7cfca0e1c384c609fa69b9b0bccb5a9":{
      "scriptId":"u49"},
    "7939d5a18cef4828b6c6c9152e345b7c":{
      "scriptId":"u50"},
    "2f09d2f0a50d44088cce20ae82e39e2f":{
      "scriptId":"u51"},
    "5b69cca382724cd98c84613adc4a1c8f":{
      "scriptId":"u52"},
    "b806b625af454f798fc4e905ea7381de":{
      "scriptId":"u53"},
    "35ac4031c13b4edbbb3f033759b78fb1":{
      "scriptId":"u54"},
    "ec05f632fc46474b9c420d7326d603bc":{
      "scriptId":"u55"},
    "2592acea48c14a56bac321e4415b47fc":{
      "scriptId":"u56"},
    "93b20d7ef8494088a7af9c670ddf48cd":{
      "scriptId":"u57"},
    "88b27d088d9046fe99846157521b3ca8":{
      "scriptId":"u58"},
    "d83f32a53a454873801435c60b3228fc":{
      "scriptId":"u59"},
    "58a3e57369fb406fa50759b5ea3a1542":{
      "scriptId":"u60"},
    "5463b7d1b0104dc7b5402b03a84dfb7f":{
      "scriptId":"u61"}}});