$axure.loadCurrentPage({
  "url":"我的资产v券2.html",
  "generationDate":new Date(1472003847956.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f5f10e1a66a04cd4aea5bd52bc1af0df",
    "type":"Axure:Page",
    "name":"我的资产V券2",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eafd3f01f4314321bd92c687edfab2b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":160},
            "size":{
              "width":450,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"344551cd245f4609a0a468582c9d2636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":160},
                "size":{
                  "width":450,
                  "height":690}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的资产v券/u0.png"}},
{
          "id":"4ed68a71f7064e19b801c7af4c58337b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":240},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27355e5ef2cb40f988aeb200e65e4778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":240},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的资产v券/u2.png"}},
{
          "id":"a7236521baf443ce8d82a196f3e6eed5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":209},
            "size":{
              "width":450,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券/u4_line.png"}},
{
          "id":"a97f9d1ace7f4995b1be490ecbbbb597",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":388,
              "y":177},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e134242f21c47b990fdc259d13055ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":388,
                  "y":177},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39cea3868e314ede838bf11cfd4ee44e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":304},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cdb0750c94cc44b49248ebca4ea71a63",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":401,
                  "y":304},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"125d22f04e1948e4a4083a4cf3962106",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":410,
              "y":328},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"645d564c5e20461aa6e640f486dacb80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":410,
                  "y":328},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"642170560d824117902caed11cc5f1d3",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":350},
            "size":{
              "width":450,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券/u11_line.png"}},
{
          "id":"022b723a8b6c4771916ad957531f523e",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":450,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券/u11_line.png"}},
{
          "id":"1b70c9436da24e7a837b7cc3b6784998",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":368},
            "size":{
              "width":44,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cf8ac7d206540598c03f49881b19437",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":368},
                "size":{
                  "width":44,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2f2333722ba9494dbf950888cc9a6947",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":524,
              "y":368},
            "size":{
              "width":48,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ef55ac881814df7babd6ec14b1f8988",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":524,
                  "y":368},
                "size":{
                  "width":48,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"90267fe6a56e4e199462bf12e8901392",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":430,
              "y":400},
            "size":{
              "width":220,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券/u17_line.png"}},
{
          "id":"aa4292f8e7fc43d2b395ad58b933fa38",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":789},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"4b1f0af637e64910982a742f8a89bf2d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":789},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 V券转赠",
                      "target":{
                        "targetType":"page",
                        "url":"v券转赠.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"a49bcc8ea1064be7bf203a65194b1982",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":183},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10fa5c07567e4f78a031003cf653b644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":183},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5c28138e78374f0abcccce2a2b51fe9f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":424},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d45de53e95249a6b7e5f218baadbfe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":424},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"486036bac42747a6a1c6d9bf9f2ced83",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":450},
            "size":{
              "width":101,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc4c43e8e6f24709b0249205f6255430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":450},
                "size":{
                  "width":101,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2b0116e656e4ff2b4a6541457a33bf8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":588,
              "y":434},
            "size":{
              "width":26,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75a4833364e245e5926235c5a6a7ecfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":588,
                  "y":434},
                "size":{
                  "width":26,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"094cd6796000450392e2e566d670b09c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":466},
            "size":{
              "width":450,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券2/u28_line.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "eafd3f01f4314321bd92c687edfab2b9":{
      "scriptId":"u0"},
    "344551cd245f4609a0a468582c9d2636":{
      "scriptId":"u1"},
    "4ed68a71f7064e19b801c7af4c58337b":{
      "scriptId":"u2"},
    "27355e5ef2cb40f988aeb200e65e4778":{
      "scriptId":"u3"},
    "a7236521baf443ce8d82a196f3e6eed5":{
      "scriptId":"u4"},
    "a97f9d1ace7f4995b1be490ecbbbb597":{
      "scriptId":"u5"},
    "3e134242f21c47b990fdc259d13055ff":{
      "scriptId":"u6"},
    "39cea3868e314ede838bf11cfd4ee44e":{
      "scriptId":"u7"},
    "cdb0750c94cc44b49248ebca4ea71a63":{
      "scriptId":"u8"},
    "125d22f04e1948e4a4083a4cf3962106":{
      "scriptId":"u9"},
    "645d564c5e20461aa6e640f486dacb80":{
      "scriptId":"u10"},
    "642170560d824117902caed11cc5f1d3":{
      "scriptId":"u11"},
    "022b723a8b6c4771916ad957531f523e":{
      "scriptId":"u12"},
    "1b70c9436da24e7a837b7cc3b6784998":{
      "scriptId":"u13"},
    "4cf8ac7d206540598c03f49881b19437":{
      "scriptId":"u14"},
    "2f2333722ba9494dbf950888cc9a6947":{
      "scriptId":"u15"},
    "1ef55ac881814df7babd6ec14b1f8988":{
      "scriptId":"u16"},
    "90267fe6a56e4e199462bf12e8901392":{
      "scriptId":"u17"},
    "aa4292f8e7fc43d2b395ad58b933fa38":{
      "scriptId":"u18"},
    "4b1f0af637e64910982a742f8a89bf2d":{
      "scriptId":"u19"},
    "a49bcc8ea1064be7bf203a65194b1982":{
      "scriptId":"u20"},
    "10fa5c07567e4f78a031003cf653b644":{
      "scriptId":"u21"},
    "5c28138e78374f0abcccce2a2b51fe9f":{
      "scriptId":"u22"},
    "0d45de53e95249a6b7e5f218baadbfe3":{
      "scriptId":"u23"},
    "486036bac42747a6a1c6d9bf9f2ced83":{
      "scriptId":"u24"},
    "cc4c43e8e6f24709b0249205f6255430":{
      "scriptId":"u25"},
    "b2b0116e656e4ff2b4a6541457a33bf8":{
      "scriptId":"u26"},
    "75a4833364e245e5926235c5a6a7ecfa":{
      "scriptId":"u27"},
    "094cd6796000450392e2e566d670b09c":{
      "scriptId":"u28"}}});