$axure.loadCurrentPage({
  "url":"我的资产v券.html",
  "generationDate":new Date(1472003847750.33),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e0a4c193ed684e879063858e41a8b619",
    "type":"Axure:Page",
    "name":"我的资产V券",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ad63006ee62a44748b952fd5f4c87ea7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":160},
            "size":{
              "width":450,
              "height":690}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4225d19d21294434a9736a9f827e5804",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":160},
                "size":{
                  "width":450,
                  "height":690}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的资产v券/u0.png"}},
{
          "id":"dbebfd371dfa415db3e8466b59e8f02b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":400,
              "y":240},
            "size":{
              "width":50,
              "height":50},
            "cornerRadiusTopLeft":"25"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bcfd9d4fc174cc7b5f82df3b2fd20a6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":400,
                  "y":240},
                "size":{
                  "width":50,
                  "height":50},
                "cornerRadiusTopLeft":"25"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的资产v券/u2.png"}},
{
          "id":"dd4e663bfa524304b856ec08a8b7abb5",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":209},
            "size":{
              "width":450,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券/u4_line.png"}},
{
          "id":"12c2a39600f84ac08eb1ebc85cf80cab",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":388,
              "y":177},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5e4bacbcac094fca9dc9dd76a5d63c5d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":388,
                  "y":177},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8d3d6d39c6b74adeb5d5e3d8c8cd8427",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":401,
              "y":304},
            "size":{
              "width":49,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d56c381c7804bee83ee74e81111c742",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":401,
                  "y":304},
                "size":{
                  "width":49,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b4742ac035bd4457aa0f6aa0ffa8f009",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"700",
            "location":{
              "x":410,
              "y":328},
            "size":{
              "width":31,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"886ac4d265d44a71ac4b5887309592dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"700",
                "location":{
                  "x":410,
                  "y":328},
                "size":{
                  "width":31,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1bf6a4c884c347bea15a180ffa684091",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":350},
            "size":{
              "width":450,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券/u11_line.png"}},
{
          "id":"d4636884d55246c5836fc49942acca53",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":450,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFD7D7D7}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券/u11_line.png"}},
{
          "id":"38c352278f4243a39f5fb75a5a7277f3",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":275,
              "y":368},
            "size":{
              "width":44,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8a6e05401bc41259073bcd3cd376ed9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":275,
                  "y":368},
                "size":{
                  "width":44,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"afb6f9da30f340038f12980ffdb59cd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":524,
              "y":368},
            "size":{
              "width":44,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b1b70eb67a6468186de96d5b6ad7a42",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":524,
                  "y":368},
                "size":{
                  "width":44,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a221c39200e041b89298f41e05dddf45",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":400},
            "size":{
              "width":220,
              "height":10},
            "borderWidth":"4",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFF0000}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/我的资产v券/u17_line.png"}},
{
          "id":"c06c944010974cd0a097794e49104ca5",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":242,
              "y":789},
            "size":{
              "width":110,
              "height":35}},
          "adaptiveStyles":{
}},
{
          "id":"d031f90d6ee447e09e0d5be2ab8449c1",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":491,
              "y":789},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 V券转赠",
                      "target":{
                        "targetType":"page",
                        "url":"v券转赠.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"1ff9cca4cb8c4e75984447f736987652",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":183},
            "size":{
              "width":32,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"715ef92faa8f4711be1d6dc1de5128c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":183},
                "size":{
                  "width":32,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "ad63006ee62a44748b952fd5f4c87ea7":{
      "scriptId":"u0"},
    "4225d19d21294434a9736a9f827e5804":{
      "scriptId":"u1"},
    "dbebfd371dfa415db3e8466b59e8f02b":{
      "scriptId":"u2"},
    "5bcfd9d4fc174cc7b5f82df3b2fd20a6":{
      "scriptId":"u3"},
    "dd4e663bfa524304b856ec08a8b7abb5":{
      "scriptId":"u4"},
    "12c2a39600f84ac08eb1ebc85cf80cab":{
      "scriptId":"u5"},
    "5e4bacbcac094fca9dc9dd76a5d63c5d":{
      "scriptId":"u6"},
    "8d3d6d39c6b74adeb5d5e3d8c8cd8427":{
      "scriptId":"u7"},
    "1d56c381c7804bee83ee74e81111c742":{
      "scriptId":"u8"},
    "b4742ac035bd4457aa0f6aa0ffa8f009":{
      "scriptId":"u9"},
    "886ac4d265d44a71ac4b5887309592dc":{
      "scriptId":"u10"},
    "1bf6a4c884c347bea15a180ffa684091":{
      "scriptId":"u11"},
    "d4636884d55246c5836fc49942acca53":{
      "scriptId":"u12"},
    "38c352278f4243a39f5fb75a5a7277f3":{
      "scriptId":"u13"},
    "a8a6e05401bc41259073bcd3cd376ed9":{
      "scriptId":"u14"},
    "afb6f9da30f340038f12980ffdb59cd4":{
      "scriptId":"u15"},
    "4b1b70eb67a6468186de96d5b6ad7a42":{
      "scriptId":"u16"},
    "a221c39200e041b89298f41e05dddf45":{
      "scriptId":"u17"},
    "c06c944010974cd0a097794e49104ca5":{
      "scriptId":"u18"},
    "d031f90d6ee447e09e0d5be2ab8449c1":{
      "scriptId":"u19"},
    "1ff9cca4cb8c4e75984447f736987652":{
      "scriptId":"u20"},
    "715ef92faa8f4711be1d6dc1de5128c7":{
      "scriptId":"u21"}}});